### ISSUE TITLE
Swift use

### ISSUE THREAD

**Issue by AgapovOne** [pjebs/Obfuscator-iOS#1]
Hello. How can i use this with swift?

Is it generated by:

```
let o = Obfuscator.newWithSaltUnsafe()
o.hexByObfuscatingString("superNEEDEDstring")
```

? or how?

**Comment by pjebs** [comment]
It's unfortunate that most of the important methods aren't bridged over to Swift. I heard in XCode 7 they may get bridged over.

You can use newWithSaltUnsafe(<**_SALT**_>) if you want but you should not UNLESS YOU KNOW WHAT YOU ARE DOING.

This is because the salt needs to be dynamically created without reference to any hard-coded strings.

My recommendation is listed here for Swift: https://github.com/pjebs/Obfuscator-iOS#step-1---generate-objective-c-code
eg. 
[Obfuscator storeKey:@"swift" forSalt:[AppDelegate class],[NSObject class],[NSString class], nil]

and then

Obfuscator.reveal(CC, usingStoredSalt: "swift")

**Comment by pjebs** [comment]
If your AppDelegate is in Swift, you can actually create an Objective C class that implements:

```
+ (void)load
{
   <PUT OBJECTIVE-C code in here>
}
```

That way it won't interfere with the rest of your swift code.

**Comment by pjebs** [comment]
Is this okay to close?

**Comment by ryancstack** [comment]
Hey, the storeKey: forSalt: doesn't bridge to swift. Is the only way around this to create the Obj-C class in the AppDelegate or create another Obj-C class?

**Comment by pjebs** [comment]
That is correct:
1) Either create AppDelegate in Obj-C OR
2) Just create a small Objective C class that does nothing more than implement the `+ (void) load` method. This is the recommended way as it is less intrusive.
In the load method, you can put objective C code that will get run when your app starts up. It is guaranteed to run only once also.

**Comment by ryancstack** [comment]
Thanks for the quick response! ended up going with 2

**Comment by Nathan187** [comment]
thanks for the suggestion (#2)...helped me as well

**Comment by RajChanchal** [comment]
I am working on a Swift project and I included this lib in my podfile. 
When I import the module, it says: Could not build Objective-C module 'Obfuscator'. What should I do?

**Comment by pjebs** [comment]
Add to bridging header
